export const BOUNCE_DURATION_THRESHOLD_SECONDS = 5;
export const ENGAGED_DURATION_THRESHOLD_SECONDS = 5;
export const ENGAGED_SCROLL_DEPTH_THRESHOLD = 30;
export const ENGAGEMENT_TIME_WEIGHT = 0.6;
export const ENGAGEMENT_SCROLL_WEIGHT = 0.4;
export const SESSION_DURATION_CAP_SECONDS = 600;
