import { Router } from "express";

import analyticsRouter from "./analytics.js";
import adminAnalyticsRouter from "./admin.analytics.js";
import adminAlertsRouter from "./admin.alerts.js";
import adminAudienceRouter from "./admin.audience.js";
import adminBillingRouter from "./admin.billing.js";
import adminDashboardRouter from "./admin.dashboard.js";
import adminInsightsRouter from "./admin.insights.js";
import adminReportsRouter from "./admin.reports.js";
import adminSettingsRouter from "./admin.settings.js";
import adminSupportRouter from "./admin.support.js";
import adminSystemRouter from "./admin.system.js";
import adminUsersRouter from "./admin.users.js";
import attributionRouter from "./attribution.js";
import audienceRouter from "./audience.js";
import authRouter from "./auth.js";
import dashboardRouter from "./dashboard.js";
import funnelRouter from "./funnel.js";
import linkRouter from "./link.js";
import metricsRouter from "./metrics.js";
import notificationsRouter from "./notifications.js";
import paymentsRouter from "./payments.js";
import reportsRouter from "./reports.js";
import sessionRouter from "./session.js";
import trackRouter from "./track.js";
import userRouter from "./users.js";
import webhooksRouter from "./webhooks.js";

const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/admin/users", adminUsersRouter);
apiRouter.use("/admin/dashboard", adminDashboardRouter);
apiRouter.use("/admin", adminBillingRouter);
apiRouter.use("/admin/analytics", adminAnalyticsRouter);
apiRouter.use("/admin/insights", adminInsightsRouter);
apiRouter.use("/admin/alerts", adminAlertsRouter);
apiRouter.use("/admin/reports", adminReportsRouter);
apiRouter.use("/admin/audience", adminAudienceRouter);
apiRouter.use("/admin/system", adminSystemRouter);
apiRouter.use("/admin/support", adminSupportRouter);
apiRouter.use("/admin/settings", adminSettingsRouter);
apiRouter.use("/users", userRouter);
apiRouter.use("/links", linkRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/metrics", metricsRouter);
apiRouter.use("/funnel", funnelRouter);
apiRouter.use("/sessions", sessionRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/attribution", attributionRouter);
apiRouter.use("/audience", audienceRouter);
apiRouter.use("/notifications", notificationsRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/webhooks", webhooksRouter);
apiRouter.use("/track", trackRouter);

export default apiRouter;
